user:
  name_length: 150
  email_length: 255
  password_length: 2
  address_length: 255
  telphone_length: 13
  avatar_size: 2
  avatar_size_display: "35x25"
  avatar_size_display_midium: "80x70"
  profile_avatar: "250x250"
travel:
  record_display: 6
  name_length: 255
  price_greater: 0
search_price:
  under_1_million: "0..1000"
  between_1_3: "1000..3000"
  between_3_6: "3000..6000"
  over_6: "6000"
number_star_default: 0
book_tour:
  record_display: 8
rating:
  record_display: 10
